# BOOTSTRAP_SERVER: "kafka1:19092"
# TOPIC: pyTest

# SLEEP: 1

# JSON_FORMAT: "utf-8"
# DATETIME_FORMAT: "%Y-%m-%d %H:%M:%S"

# EVENT:
#   MESSAGE: "hello!"
#   METRIC_ID_MIN: 1
#   METRIC_ID_MAX: 10
#   METRIC_VALUE_MIN: 1
#   METRIC_VALUE_MAX: 100
#   REPORTER_ID_START: 1
#   REPORTER_ID_INCREMENT: 1

BOOTSTRAP_SERVER: "localhost:9092"
TOPIC: dev
SLEEP: 1

JSON_FORMAT: "utf-8"
DATETIME_FORMAT: "%Y-%m-%d %H:%M:%S"

EVENT:
  MESSAGE: "hello!"
  METRIC_ID_MIN: 1
  METRIC_ID_MAX: 10
  METRIC_VALUE_MIN: 1
  METRIC_VALUE_MAX: 100
  REPORTER_ID_START: 1
  REPORTER_ID_INCREMENT: 1
